name: Deploy Vue App to Hostinger

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies & Build
      run: |
        npm install
        npm run build

    - name: Deploy via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        port: ${{ secrets.SFTP_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist/*"
        target: "/home/u173510456/domains/moccasin-ape-145176.hostingersite.com/public_html/"
